# 描述Compose文件的版本信息
version: '3.8'

# 定義服務，可以多個
services:
  react-admin-server:
    build: # 指定根據哪個Dockerfile構建容器
      context: ./
      dockerfile: react-admin-server/Dockerfile
    image: react-admin-server  #鏡像名稱
    container_name: react-admin-server
    environment:
      - TZ=Asia/Shanghai
    command:
      - --rm
    ports: # 宿主機和容器的端口映射關係
      - "5000:5000" # 左邊宿主機端口:右邊容器端口
    networks: # 配置容器連接的網絡，引用頂級networks下的條目
      - backend
    restart: always
    depends_on:
      - mongodb
  mongodb: # mysql服務
    image: mongo
    container_name: mongo
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
    ports: # 宿主機和容器的端口映射關係
      - "27017:27017" # 左邊宿主機端口:右邊容器端口
    networks: # 配置容器連接的網絡，引用頂級networks下的條目
      - backend
    restart: always
# 定義網絡，可以多個，如果不聲明，默認會創建一個網絡名稱為“工程名稱_default”的bridge網絡
networks:
  backend: # 一個具體網絡的條目名稱
    name: backend # 網絡名稱，默認為“工程名稱_網絡條目名稱”
    driver: bridge # 網絡模式，默認為bridge